### ISSUE TITLE
Yarn Bundle fails with http dependency using Yarn 3.1.0 & WSL 2

### ISSUE THREAD

**Issue by Laberbear** [ojkelly/yarn.build#142]
**Describe the bug**
I'm using yarn.build in a project with quite a few workspaces. 

We have a dependency which is retrieved via http (git repository) which contains built protobuf files.

Yarn install works fine but as soon as I run yarn bundle it throws this error:
winbuntu@DESKTOP:~/work/project/package-a$ yarn bundle
Internal Error: ENOENT: no such file or directory, chmod '/tmp/xfs-70aa0113/node_modules/@a/b/c/d/e.proto'
Error: ENOENT: no such file or directory, chmod '/tmp/xfs-70aa0113/node_modules/@a/b/c/d/e.proto'

Not sure whether this is related to WSL2 or the git dependency.

Yarn Version: 3.1.0
OS: WSL 2 (Ubuntu 20)
Node Version: 14
.yarnrc file:
```
nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@ojkelly/plugin-build.cjs
    spec: "https://yarn.build/latest"

yarnPath: .yarn/releases/yarn-3.1.0.cjs

```

Thanks in advance
